from pydantic.v1 import BaseModel, Field

class TableFinderSchema(BaseModel):
    pdf_path: str = Field(description="The full file path to the PDF document to be analyzed.")

class DataExtractorSchema(BaseModel):
    raw_table_data: str = Field(description="A string containing the raw, unprocessed text of a table found in a PDF.")

class ValidationSchema(BaseModel):
    raw_table_data: str = Field(description="The original, raw text of the table.")
    generated_csv: str = Field(description="The final CSV data generated by the extractor tool.")
